#ifndef INPUT_PROXY_VERSION_H
#define INPUT_PROXY_VERSION_H

#define INPUT_PROXY_VERSION_MAJOR 0
#define INPUT_PROXY_VERSION_MINOR 1
#define INPUT_PROXY_VERSION_PATCH 0

#define INPUT_PROXY_VERSION_STRING "0.1.0"

#endif